name: deploy s3
on:
    push:
        branches:
            - main
jobs: 
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [15.x]
        steps:
            - uses: action/checkout@v1
            - run: npm install
            - run: npm run build
            - run: npm test